### ISSUE TITLE
`curvespoints` not in `plist['$objects'][8]`

### ISSUE THREAD

**Issue by dw61** [mrandri19/notability2svg-python#1]
I converted my `Session.plist` using `plutil -convert xml1 Session.plist` (this was in-place) and ran `Session.plist`, but it seems curvespoints isn't in `dict_with_data`. I tried other elements in `plist['$objects']` list but didn't find curvespoints.

**Comment by dw61** [comment]
[Session.txt](https://github.com/mrandri19/notability2svg-python/files/7470962/Session.txt)
This is my `Session.plist` (GitHub doesn't support `.plist`, so I named it `Session.txt`)

**Comment by dw61** [comment]
Any help for my reverse engineering attempt? Thanks!

**Comment by mrandri19** [comment]
I tried searching into the file for `curvespoints` and I found that key so it must be somewhere.

Btw I have found that converting to PDF and then extracting the SVGs embedded in the PDF with Inkscape is by far the easiest method.

**Comment by dw61** [comment]
That make sense!! I also see `curvespoints` in my `plist`, didn't thought about it this way. By converting to PDF, do you refer to [this](https://github.com/dvdblk/notability-notes-converter) repo, or do you do it directly within notability app? Thank you!

**Comment by mrandri19** [comment]
I just email myself the note as a PDF from the Notability app. You can do it from the share menu.

**Comment by dw61** [comment]
Sounds good! Thank you very much!!
